# Calls into the external `tcl_library` generated by
# `@nagelfar_external_pkg`. Nagelfar must see the external target's
# syntaxdb — otherwise `external_pkg::hello` would be flagged as an
# unknown command and the aspect check would fail.

namespace eval consumer {
    proc greet {} {
        return [external_pkg::hello "hi"]
    }
}
