load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("//tcl:tcl_test.bzl", "tcl_test")
load("//tcl/nagelfar:tcl_nagelfar_test.bzl", "tcl_nagelfar_test")

write_file(
    name = "generated_file",
    out = "generated_data.txt",
    content = ["La-Li-Lu-Le-Lo"],
    newline = "unix",
)

tcl_test(
    name = "runfiles_test",
    srcs = ["runfiles_test.tcl"],
    data = [
        "data.txt",
        ":generated_data.txt",
    ],
    env = {
        "DATA_RLOCATIONPATH": "$(rlocationpath data.txt)",
        "GENERATED_DATA_RLOCATIONPATH": "$(rlocationpath :generated_data.txt)",
    },
    deps = ["//tcl/runfiles"],
)

tcl_test(
    name = "runfiles_unit_test",
    srcs = ["runfiles_unit_test.tcl"],
    deps = ["//tcl/runfiles"],
)

tcl_nagelfar_test(
    name = "runfiles_nagelfar",
    target = "//tcl/runfiles",
)
