load("@rules_tcl//tcl:tcl_toolchain.bzl", "tcl_toolchain", "tclcore_filegroup")

tclcore_filegroup(
    name = "tclcore",
    srcs = ["@tcl_lang//:tcl_core"],
)

tcl_toolchain(
    name = "tcl_toolchain",
    tclcore = ":tclcore",
    tcllib = "@tcllib",
    tclsh = "@tcl_lang//:tclsh",
    wrapper_entrypoint = "@rules_tcl//tcl/private:entrypoint.tcl",
    wrapper_template = "@rules_tcl//tcl/private:binary_wrapper.tpl",
)

toolchain(
    name = "toolchain",
    toolchain = ":tcl_toolchain",
    toolchain_type = "@rules_tcl//tcl:toolchain_type",
)
