"""examples"""

module(
    name = "rules_tcl_examples",
    version = "0.0.0",
)

bazel_dep(name = "rules_tcl", version = "0.0.0")
local_path_override(
    module_name = "rules_tcl",
    path = "../",
)

bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "tcl_lang", version = "9.0.2.bcr.1")

tcllib_ext = use_extension("@rules_tcl//tcl:extensions.bzl", "tcllib")
use_repo(tcllib_ext, "tcllib")

register_toolchains(
    "//toolchain",
)
