"""Public rules for tcllib."""

load(":providers.bzl", "TclLibInfo")
load(":toolchain.bzl", "rlocationpath")

_PKG_INDEX_TEMPLATE = """\
# Tcl package index file, version 1.1
# Do NOT edit by hand. Generated by rules_tcl.

if {{![package vsatisfies [package provide Tcl] 8.5 9]}} return

if {{$dir ni $::auto_path}} {{
    lappend ::auto_path $dir
}}

package ifneeded tcllib {version} {{package provide tcllib {version}}}

apply {{{{maindir}} {{
    foreach subpkg [glob -nocomplain -directory $maindir -type d -tails *] {{
        set dir [file join $maindir $subpkg]
        set indexfile [file join $dir pkgIndex.tcl]
        if {{[file exists $indexfile]}} {{
            source $indexfile
        }}
    }}
}}}} $dir
"""

def _tcllib_filegroup_impl(ctx):
    prefix = ctx.attr.prefix

    pkg_index = ctx.actions.declare_file(prefix + "/modules/pkgIndex.tcl")
    ctx.actions.write(
        output = pkg_index,
        content = _PKG_INDEX_TEMPLATE.format(version = ctx.attr.version),
    )

    outputs = [pkg_index]
    for src in ctx.files.srcs:
        out = ctx.actions.declare_file("{}/{}".format(prefix, src.owner.name))
        ctx.actions.symlink(output = out, target_file = src)
        outputs.append(out)

    include = rlocationpath(pkg_index, ctx.workspace_name)[:-len("/pkgIndex.tcl")]

    return [
        DefaultInfo(
            files = depset(outputs),
            runfiles = ctx.runfiles(files = outputs),
        ),
        TclLibInfo(
            pkg_index = pkg_index,
            include = include,
        ),
    ]

tcllib_filegroup = rule(
    doc = "Stages a tcllib source tree under a prefix and generates a pkgIndex.tcl that auto-discovers sub-packages.",
    implementation = _tcllib_filegroup_impl,
    attrs = {
        "prefix": attr.string(
            doc = "Directory prefix to stage the tcllib tree under.",
            mandatory = True,
        ),
        "srcs": attr.label_list(
            allow_files = True,
            doc = "Files from the tcllib `modules/` tree.",
            mandatory = True,
        ),
        "version": attr.string(
            doc = "The tcllib version, used in the generated pkgIndex.tcl.",
            mandatory = True,
        ),
    },
)
