load("//tcl:tcl_toolchain.bzl", "TOOLCHAIN_TYPE", "tcl_toolchain", "tclcore_filegroup")

tclcore_filegroup(
    name = "tclcore",
    srcs = ["@tcl_lang//:tcl_core"],
)

tcl_toolchain(
    name = "tcl_toolchain",
    tclcore = ":tclcore",
    tcllib = "@tcllib",
    tclsh = "@tcl_lang//:tclsh",
    visibility = ["//visibility:public"],
    wrapper_entrypoint = "//tcl/private:entrypoint.tcl",
    wrapper_template = "//tcl/private:binary_wrapper.tpl",
)

toolchain(
    name = "toolchain",
    toolchain = ":tcl_toolchain",
    toolchain_type = TOOLCHAIN_TYPE,
    visibility = ["//visibility:public"],
)
